on:
  release:
    types:
      - "published"

# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
# release.name / tag_name release-name until `:`
jobs:
  upload_assets:
    name: Ceate/Upload assets
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v3
      # - name: Set up Python and PDM
      #   uses: pdm-project/setup-pdm@main
      #   with:
      #     python-version: 3.10
      - name: Echo release
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event }}
          echo ${{ github.event.release }}
          echo ${{ github.event.release.tag_name }}
          echo ${{  startsWith( github.event.release.name, 'package_a' )}}
