on:
  push:
    branches:
      - "main"
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # probably equivalent to:
          # manifest-release which isn't deprecated yet?
          command: manifest
          release-type: python
          # Ensure that that I can release multiple packages form one repository
          monorepo-tags: true
          # https://github.com/google-github-actions/release-please-action#manifest-release-output
          # According to their documentation it looks like they are expecting
          # to continue the publication after this...
          # separate-pull-requests: true
      # 1. git checkout
      # 2. Install PDM whenever a release is created
      # 3. maybe build/test package publishing running it?
      # 4. publish via PDM

      # just for debugging purposes
      - run: |
          echo "A release was created"
          echo ${{ toJSON(steps.release.outputs.paths_released) }}
          echo ${{ contains(steps.release.outputs.paths_released, 'package_a') }}
        if: ${{ steps.release.outputs.releases_created }}
